[changelog]
header = """
# Changelog\n
All notable changes to this project are documented in this file.\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% set grouped = commits | group_by(attribute="group") %}
{% for group_name in ["Features", "Bug Fixes", "Performance", "Refactoring", "Documentation", "Testing", "Continuous Integration", "Miscellaneous Tasks", "Other"] %}
{% if group_name in grouped %}
    ### {{ group_name }}
    {% for commit in grouped[group_name] %}
        - {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](../../commit/{{ commit.id }}))\
    {% endfor %}
{% endif %}
{% endfor %}\n
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = []
commit_parsers = [
    { message = "(?i)^chore:\\s*release", skip = true },
    { message = "(?i)^feat", group = "Features" },
    { message = "(?i)^fix", group = "Bug Fixes" },
    { message = "(?i)^refactor", group = "Refactoring" },
    { message = "(?i)^chore", group = "Miscellaneous Tasks" },
    { message = "(?i)^docs", group = "Documentation" },
    { message = "(?i)^test", group = "Testing" },
    { message = "(?i)^ci", group = "Continuous Integration" },
    { message = "(?i)^perf", group = "Performance" },
    { message = ".*", group = "Other" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9]*"
topo_order = false
sort_commits = "oldest"
